project:
  type: website
  output-dir: docs

website:
  title: "Rylan Mueller"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: media/resume.pdf
        text: Resume
      - text: "Capstones"
        menu:
          - text: "Population Inference Using a Hidden Markov Model Approach"
            href: projects/StatisticalGenetics/StatisticalGeneticsCapstone.qmd
          - text: "Spending in Vain? The Effect of Spending in the 2016 and 2020 US Presidential Elections"
            href: projects/PoliticalScience/PoliticalScienceCapstone.pdf
          - text: "Food Accessibility in Minneapolis: A Study of Public Transit"
            href: projects/DataScience/DataScienceCapstone.qmd

format:
  html:
    htmlwidgets: true
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: source

